apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
      - image: leave-vacation/rhoar-employee-microservice:1.0
        name: ${project.artifactId}
        ports:
        - containerPort: 8080
        env:
        - name: DB_USERNAME
          valueFrom:
             secretKeyRef:
               name: my-database-secret
               key: user
        - name: DB_PASSWORD
          valueFrom:
             secretKeyRef:
               name: my-database-secret
               key: password
        - name: JAVA_OPTIONS
          value: "-Dspring.profiles.active=openshift"
      - image: jaegertracing/jaeger-agent
        name: jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        command:
        - /go/bin/agent-linux
        - '--collector.host-port=jaeger-collector.leave-vacation.svc:14267'